
const bikes = [
 {
  
  make: "Harley Davidson",
  model: "Breakout 117",
  year: 2023,
  price: 26549.00,
  image: "/pictures/HarleyDavidson/Breakout117.png",
 },
 {
  make: "Harley Davidson",
  model: "CVO Road Glide",
  year: 2023,
  price: 42999.00,
  image: "/pictures/HarleyDavidson/CVORoadGlide.png",
 },
 {
  make: "Harley Davidson",
  model: "CVO Pan America",
  year: 2024,
  price: 34599.00,
  image: "/pictures/HarleyDavidson/CVOPanAmerica.png",
 },
 {
  make: "Harley Davidson",
  model: "Electra Glide Highway King",
  year: 2023,
  price: 32999.00,
  image: "/pictures/HarleyDavidson/ElectraGlideHighwayKing.png",
 },
 {
  make: "Yamaha",
  model: "YZF-R1",
  year: 2020,
  price: 12902.00,
  image: "/pictures/Yamaha/YZFR1.png",
 },
 {
  make: "Yamaha",
  model: "MT-03",
  year: 2020,
  price: 4599.00,
  image: "/pictures/Yamaha/MT03.png",
 },
 {
  make: "Yamaha",
  model: "FJR1300ES",
  year: 2022,
  price: 21560.00,
  image: "/pictures/Yamaha/FJR1300ES.png",
 },
 {
  make: "Yamaha",
  model: "Tenere 700",
  year: 2019,
  price: 13999.00,
  image: "/pictures/Yamaha/Tenere700.png",
 },
 {
  make: "Kawasaki",
  model: "Ninja H2",
  year: 2014,
  price: 38999.00,
  image: "/pictures/Kawasaki/NinjaH2.png",
 },
 {
  make: "Kawasaki",
  model: "W800",
  year: 2020,
  price: 11999.00,
  image: "/pictures/Kawasaki/W800.png",
 },
 {
  make: "Kawasaki",
  model: "1400GTR",
  year: 2007,
  price: 15600.00,
  image: "/pictures/Kawasaki/1400GTR.png",
 },
 {
  make: "Kawasaki",
  model: "Vulcan S ABS",
  year: 2015,
  price: 8699.00,
  image: "/pictures/Kawasaki/VulcanSABS.png",
 },
 {
  make: "Ducati",
  model: "Panigale V2",
  year: 2024,
  price: 21995.00,
  image: "/pictures/Ducati/PanigaleV2.png",
 },
 {
  make: "Ducati",
  model: "Superleggera V4",
  year: 2020,
  price: 100000.00,
  image: "/pictures/Ducati/SuperleggeraV4.png",
 },
 {
  make: "Ducati",
  model: "Monster",
  year: 2021,
  price: 12995.00,
  image: "/pictures/Ducati/Monster.png",
 },
 {
  make: "Ducati",
  model: "DesertX",
  year: 2022,
  price: 23095.00,
  image: "/pictures/Ducati/DesertX.png",
 },
 {
  make: "Ural",
  model: "Gear-up 2WD",
  year: 2005,
  price: 17289.00,
  image: "/pictures/Ural/Gearup2WD.png",
 },
 {
  make: "Ural",
  model: "Weekender",
  year: 2021,
  price: 20629.00,
  image: "/pictures/Ural/Weekender.png",
 },
 {
  make: "Ural",
  model: "City",
  year: 2015,
  price: 5925.00,
  image: "/pictures/Ural/City.png",
 },
 {
  make: "Ural",
  model: "Patrol 2WD",
  year: 2006,
  price: 6719.00,
  image: "/pictures/Ural/Patrol2WD.png",
 },
];

module.exports = bikes;
